name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository files
        run: |
          echo "Files in my repository:"
          ls -la

      - name: Read README
        run: cat README.md
