name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check operating system
        run: |
          echo "Hello from GitHub Actions!"
          echo "I am running on:"
          uname -a

      - name: Check current directory
        run: pwd

      - name: List files
        run: ls -la
